import coinLogo from '@/assets/image/bitcoin.png'

const textAboutCoin = `Farm Airdrops at the click of a button. Sybulls is a first-of-its-kind automated airdrop farming toolkit. Sybulls is a first-of-its-kind automated airdrop farming toolkit. With our platform, you can continuously farm airdrops from the top DeFi projects in the space.

Benefits:

Holding $SYBL grants you a 30% revenue share with the protocol
Revenue is generated through multiple sources discussed below

Revenue Sources - Platform usage fees, .011 ETH per wallet per month to use the software.

$SYBL Volume Rewards. 1% of fees generated from token taxes go directly to holders

Airdrop Rewards. Free users are able to use the platform in return for 20% of any airdrops they receive. We share this 20% among all token holders with 50% of these airdrop returns being distributed to holders directly. Snapshots for airdrop returns are taken at the time the airdrop is distributed.

REDACTED. 50% of fees generated by REDACTED will be distributed to holders.

Airdrop Rewards. Free users are able to use the platform in return for 20% of any airdrops they receive. We share this 20% among all token holders with 50% of these airdrop returns being distributed to holders directly. Snapshots for airdrop returns are taken at the time the airdrop is distributed.

REDACTED. 50% of fees generated by REDACTED will be distributed to holders.

Legal. This does not constitute financial advice nor should this be considered an investment. Sybulls makes no guarantees neither express or implied. $SYBL is a utility token which grants discounts to the platform and nothing further.`

export const dataTable = [
    {
        tokenName: 'Candy Chain Coin (WCCC)',
        contract: '0x70A8546f70d404AFa13912CD4f35584f56fe03cc',
        toUpdate: {
            name: 'Coin (WCCC)',
            logoSrc: coinLogo,
            about: textAboutCoin,
            website: 'http:/test',
            discord: 'discordTest',
            facebook: 'facebookTest',
        },
    },
    {
        tokenName: 'Candy ChCCC)Candy ChCCC)Candy ChCCC)',
        contract: '0x70A8546f70d404AFa13912CD4f35584f56fe03cc',
        toUpdate: {
            name: 'Candy ChCCC)Candy ChCCC)Candy ChCCC)Candy ChCCC)',
            logoSrc: coinLogo,
            about: textAboutCoin,
            website: 'http:/testCandyChCCC)Candy ChCCC)',
            discord: 'discordTestdiscordTestdiscordTest',
            facebook: 'facebookTestfacebookTestfacebookTest',
        },
    },
    {
        tokenName: 'CandCC)CandCCCandCCCandCC',
        contract: '0x70A8546f70d404AFa13912CD4f35584f56fe03cc',
        toUpdate: {
            name: 'Coin (WCCC)',
            logoSrc: coinLogo,
            about: 'textAboutCoin',
            website: 'http:/test',
            discord: 'discordTest',
            facebook: 'facebookTest',
        },
    },
    {
        tokenName: 'CandCC)CandCCCandCCCandCC',
        contract: '0x70A8546f70d404AFa13912CD4f35584f56fe03cc',
        toUpdate: {
            name: 'Coin (WCCC)',
            logoSrc: coinLogo,
            about: textAboutCoin,
            website: 'http:/test',
            discord: 'discordTest',
            facebook: 'facebookTest',
        },
    },
]

export type TDataTable = typeof dataTable
